# Generated by Django 2.2.5 on 2019-10-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
