# Generated by Django 2.2.5 on 2019-10-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20191013_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='suppliers',
        ),
    ]
