# Generated by Django 2.2.5 on 2019-10-09 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department_profile',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.Department'),
        ),
    ]
