# Generated by Django 2.2.5 on 2019-10-10 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20191009_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.Department'),
        ),
    ]
