# Generated by Django 2.2.5 on 2019-10-10 17:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=30, verbose_name='Tipo De Documento')),
                ('number', models.BigIntegerField(verbose_name='Numero De Documento')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('payday', models.DateField(verbose_name='Dia De Pago')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha De Actualizacion')),
                ('expiration', models.DateField(verbose_name='Vencimiento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created'],
            },
        ),
    ]
