# Generated by Django 2.2.5 on 2019-10-10 19:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Nombre Servicio')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('file', models.ImageField(upload_to='archivos', verbose_name='Archivo')),
                ('number', models.BigIntegerField(verbose_name='Numero De Proyecto')),
                ('expiration', models.DateField(verbose_name='Vencimiento')),
                ('payday', models.DateField(verbose_name='Dia De Pago')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha De Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha De Actualizacion')),
            ],
            options={
                'verbose_name': 'servicios',
                'verbose_name_plural': 'servicios',
                'ordering': ['-created'],
            },
        ),
    ]
