# Generated by Django 2.2.5 on 2019-10-10 20:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='expiration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='archivos', verbose_name='Archivo PDF/CSV/.. etc.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='payday',
            field=models.DateField(),
        ),
    ]
