# Generated by Django 2.2.5 on 2019-10-13 00:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('departments', models.CharField(blank=True, max_length=30, null=True, verbose_name='Departamento')),
                ('suppliers', models.CharField(max_length=20, verbose_name='Proveedor')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('quantity', models.IntegerField(default=2, verbose_name='Cantidad')),
                ('image', models.ImageField(upload_to='services', verbose_name='imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha De Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha De Actualizacion')),
            ],
        ),
    ]
